### ISSUE TITLE
Plan output missing module name for destroys

### ISSUE THREAD

**Issue by joe-boyce** [coinbase/terraform-landscape#100]
Hi,

I've have just been testing out landscape which works great but noticed that the plan output for a destroy on a module is missing the actual module in the plan output:

**Normal output:**

```
An execution plan has been generated and is shown below.

Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

- module.test_sa.google_service_account.serviceaccount
Plan: 0 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

**Landscape output**

```
plan | landscape
Plan: 0 to add, 0 to change, 1 to destroy.
```

Am I missing something or does landscape not support this?

Thanks,

Joe

**Comment by sds** [comment]
Happy to accept a pull request fixing the parser, @joe-boyce!

**Comment by tkbky** [comment]
It works fine for me.
I can't reproduce this with

Deps | Version
-- | -- |
terraform | v0.11.11 |
terraform-landscape | master |

@joe-boyce which version of terraform and landscape are you on?
@sds FYI
