### ISSUE TITLE
Occasionally get error: Can't find a diff executable in PATH

### ISSUE THREAD

**Issue by Draftkings** [coinbase/terraform-landscape#105]
Sometimes when I try to run `terraform plan | landscape` on Windows I get the follow error 

`error: Can't find a diff executable in PATH`

I've seen this occur when trying to diff the `policy` attribute of an `aws_iam_policy`

Setup

- Terraform v0.11.14
  - provider.aws v2.14.0
- terraform_landscape (0.3.2)

**Comment by sds** [comment]
`diff` doesn't ship by default on Windows environments. See the [following suggestions](https://github.com/samg/diffy#on-windows) for how to get an appropriate `diff` installed in your environment.
