### ISSUE TITLE
Support customizable formatters for resource diffs

### ISSUE THREAD

**Issue by sds** [coinbase/terraform-landscape#108]
A number of issues boil down to the desire to implement customizations around how the resource diff is presented. Linked are some issues below, which we're folding into this one master issue to track:

* #60
* #70
* #72
* #74
* #87

It's important that we not insert any of the logic in the default code path, as there are some situations where certain formatting functionality may not be desired. It would be ideal to have this be customizable on a per-resource type basis.

This would likely mean the introduction of a configuration file of some sort, and an ability to import custom formatters without needing to contribute to this project directly.

This ticket is open for anyone to take, just wanted to consolidate open issues into one trackable place.

**Comment by Thompsonyo** [comment]
I need help to login into my coinbase I don't have access to number but I have my Gmail

**Comment by InitialSupport** [comment]
We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6

**Comment by CustomerTeam001** [comment]
> I need help to login into my coinbase I don't have access to number but I have my Gmail 

 We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77

**Comment by sds** [comment]
I no longer am employed at Coinbase (for many years). Closing since this was created by me but I have no intention of implementing.
