### ISSUE TITLE
openSSL

### ISSUE THREAD

**Issue by LiamMcManus** [coinbase/terraform-landscape#113]
Hi, why does terraform-landscape has a dependency on openSSL?

**Comment by sds** [comment]
Hey @LiamMcManus, this project does not explicitly depend on OpenSSL. See the [gemspec](https://github.com/coinbase/terraform-landscape/blob/master/terraform_landscape.gemspec) for a list of dependencies.

What you are likely seeing (though there is not enough information provided in this issue to confirm) is an error related to Ruby's dependency on OpenSSL, which is unrelated to this project. Again, unclear based on the question posed, but likely what you are seeing.
