### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/terraform-landscape#115]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/terraform-landscape/compare/106c2933e0f79ae737e6d7a8b1d0a300e0b3c134...46a754d7a8e6c704203ee1cb10624bdff0b90974) was merged to master by sds.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/terraform-landscape&ref=46a754d7a8e6c704203ee1cb10624bdff0b90974)

**Comment by MrSaints** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for MrSaints @ 2020-06-25 09:53:31 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Comment by nejoshi** [comment]
👍

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 1/1
------------ | -------------
nejoshi | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/terraform-landscape&ref=46a754d7a8e6c704203ee1cb10624bdff0b90974)
