### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by owensj8** [coinbase/terraform-landscape#116]
When I try to run landscape I get a parsing error. The terraform plan on its' own is successful so not sure what this could be.
'''
❯ tf12 plan | landscape
Terraform Landscape: a parsing error occured. Falling back to original Terraform output...
'''
On another issue that seems related i saw an option to grab a trace which I did.

'''
❯ tf12 plan | landscape --trace
Traceback (most recent call last):
        13: from /usr/local/bin/landscape:23:in `<main>'
        12: from /usr/local/bin/landscape:23:in `load'
        11: from /var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/bin/landscape:7:in `<top (required)>'
        10: from /var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/lib/terraform_landscape/cli.rb:25:in `run'
         9: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
         8: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/runner.rb:68:in `run!'
         7: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
         6: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
         5: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
         4: from /var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/lib/terraform_landscape/cli.rb:34:in `block (2 levels) in define_commands'
         3: from /var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/lib/terraform_landscape/cli.rb:53:in `print'
         2: from /var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/lib/terraform_landscape/printer.rb:42:in `process_stream'
         1: from /var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/lib/terraform_landscape/printer.rb:99:in `process_string'
/var/lib/gems/2.5.0/gems/terraform_landscape-0.3.3/lib/terraform_landscape/terraform_plan.rb:40:in `from_output': Expected one of [\s], [ ], '~', '-/+', '-', '+', '<=' at line 3, column 3 (byte 5) after  (TerraformLandscape::TerraformPlan::ParseError)
'''

**Comment by sds** [comment]
Hey @owensj8, as mentioned in the [README](https://github.com/coinbase/terraform-landscape#requirements), Landscape does not support Terraform 0.12 at this time. Would welcome a pull request adding support!
