### ISSUE TITLE
terraform 0.14 concise renderer

### ISSUE THREAD

**Issue by mwarkentin** [coinbase/terraform-landscape#117]
Opening a new issue since #101 is locked.

It looks like terraform is building in some native support for improved diffs:

* https://github.com/hashicorp/terraform/releases/tag/v0.14.0-alpha20200910
* https://discuss.hashicorp.com/t/terraform-0-14-concise-plan-diff-feedback-thread/14004

**Comment by sds** [comment]
We're very excited to see support for concise diffs land in Terraform 0.14. 

Being explicit: we would strongly encourage anyone looking to improve diff readability to pursue upgrading to Terraform 0.14 rather than rely on Terraform Landscape.

Closing as informational. Thanks!
