### ISSUE TITLE
run landscape with terraform container

### ISSUE THREAD

**Issue by SydOps** [coinbase/terraform-landscape#16]
I run terraform with `docker run` container, any suggestions to get it work?

>$ docker run -ti --rm -w /app -v $HOME/.aws:/root/.aws  -v /projects:/app hashicorp/terraform:0.9.1 plan -input=false | landscape
error: Expected one of [\S], [ ], "\n", "\n\n" at line 1, column 39 (byte 39) after ~ module.main.aws_autoscaling_group.main. Use --trace to view backtrace

**Comment by sds** [comment]
Hey @SydOps,

This is difficult to debug without having an example of the output. If you can produce sample output by running `docker run ... > output.txt` and then `cat output | landscape` to reproduce the problem, you can then send us `output.txt` and we can reproduce locally.

Also, please ensure you are running the latest version of `landscape` ([0.1.4](https://github.com/coinbase/terraform-landscape/releases/tag/v0.1.4) at time of writing). Thanks!

**Comment by SydOps** [comment]
Thanks, @sds 

I did a test with the latest landscape, attach the output here. 

[output.tar.gz](https://github.com/coinbase/terraform-landscape/files/956830/output.tar.gz)

In attach output, there are two files

`output.cmd` - generated by `terraform plan > output.cmd`

`output.run` - generated by ` docker run -ti --rm -w /app -v $HOME/.aws:/root/.aws -v `pwd`:/app hashicorp/terraform:0.9.1 plan > output.run`

**Comment by sds** [comment]
Thanks for providing that additional output, @SydOps.

The issue was your output included Windows line endings (`\r\n`) which our parser's grammar was not written to support.

This has been fixed in [0.1.5](https://github.com/coinbase/terraform-landscape/releases/tag/v0.1.5). Thanks again for the report!

**Comment by SydOps** [comment]
That's interesting. I run the command on a mac book.

**Comment by SydOps** [comment]
did a test with version 0.1.5, it works now, thanks.
