### ISSUE TITLE
When using interactive input, landscape stalls

### ISSUE THREAD

**Issue by joscha** [coinbase/terraform-landscape#18]
When using terraform plans that expect input variables, e.g.
```
$ terraform apply

var.ami
  Enter a value: ami-XXXXX

var.count
  Enter a value: 5

var.metadata
  Enter a value: role=yyyy
```

then running this output through landscape hides the fact that the `plan`/`apply` is waiting for such input. I am not sure if there is an easy way for landscape to detect this, but if there is, printing at least a warning would be great.

**Comment by sds** [comment]
Hey @joscha, 

This isn't a workflow we deal with at Coinbase, but we'd be happy to accept a pull request that detects this case or allows you to provide input. Thanks!

**Comment by joscha** [comment]
Understood @sds - not sure my shell-fu is strong enough, but will check :) I'll close this in the meantime.
