### ISSUE TITLE
Question about terraform upstream

### ISSUE THREAD

**Issue by pgporada** [coinbase/terraform-landscape#21]
Have you thought about showing the upstream terraform folks this? This seems like something that would be useful in core terraform.

**Comment by sds** [comment]
This project was mentioned in one of the (many) diff-improvement related issues in Terraform: https://github.com/hashicorp/terraform/issues/5008#issuecomment-283202461

It's up to the Terraform project whether the approach taken here is something they would like to embrace, but it still requires someone proficient in Go to implement.
