### ISSUE TITLE
Cryptically doesn't work if no `-out` param is used

### ISSUE THREAD

**Issue by glenjamin** [coinbase/terraform-landscape#3]
It would be nice if this could work without needing the `Path: ` string to find the start of the plan, but failing that could you add a note the the readme or the error text which mentions that `-out` is required for this tool to work?

It might be possible to begin processing from the first line which looks like a resource header instead?

Cheers!

**Comment by sds** [comment]
Thanks for the report, @glenjamin!

This was a silly oversight on my part. We've fixed the issue and rolled out a [new release](https://github.com/coinbase/terraform-landscape/releases/tag/v0.1.0).
