### ISSUE TITLE
Issues running with lastest terraform v0.10.4 ?

### ISSUE THREAD

**Issue by colincampbell1967** [coinbase/terraform-landscape#30]
Terraform is outputing 

> ------------------------------------------------------------------------
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   ~ module.log-ingest-tf.aws_s3_bucket_policy.log-ingest-bucket-policy
>       policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"E
> 
This is causing the following error error: Expected [ ] at line 2, column 2 (byte 3) after 
-. Use --trace to view backtrace

withe the trace 

[me@localhost tf]$ terraform plan | landscape 
error: Expected [ ] at line 2, column 2 (byte 3) after 
-. Use --trace to view backtrace
[colincampbell@localhost tf]$ terraform plan | landscape --trace
/home/me/.gem/ruby/gems/terraform_landscape-0.1.10/lib/terraform_landscape/terraform_plan.rb:36:in `from_output': Expected [ ] at line 2, column 2 (byte 3) after  (TerraformLandscape::TerraformPlan::ParseError)
-
	from /home/me/.gem/ruby/gems/terraform_landscape-0.1.10/lib/terraform_landscape/printer.rb:59:in `process_string'
	from /home/me/.gem/ruby/gems/terraform_landscape-0.1.10/lib/terraform_landscape/printer.rb:35:in `process_stream'
	from /home/me/.gem/ruby/gems/terraform_landscape-0.1.10/lib/terraform_landscape/cli.rb:48:in `print'
	from /home/me/.gem/ruby/gems/terraform_landscape-0.1.10/lib/terraform_landscape/cli.rb:34:in `block (2 levels) in define_commands'
	from /home/me/.gem/ruby/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /home/me/.gem/ruby/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /home/me/.gem/ruby/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /home/me/.gem/ruby/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /home/me/.gem/ruby/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /home/me/.gem/ruby/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /home/me/.gem/ruby/gems/terraform_landscape-0.1.10/lib/terraform_landscape/cli.rb:25:in `run'
	from /home/me/.gem/ruby/gems/terraform_landscape-0.1.10/bin/landscape:7:in `<top (required)>'
	from /home/me/bin/landscape:23:in `load'
	from /home/me/bin/landscape:23:in `<main>'

**Comment by NathanTCz** [comment]
After some testing, there are two things breaking this.

## Issue 1
Two parts of the output are breaking it, specifically (in bold):

**------------------------------------------------------------------------**

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  **[32m+[0m create
 [36m<=[0m read (data resources)
[0m**
Terraform will perform the following actions:

I know this probably isn't the right way to go about it, but if you were to strip that header in `TerraformLandscape::Printer.process_string` where you are stripping the rest of the header:
```ruby
def process_string(plan_output)
  scrubbed_output = plan_output.gsub(/\e\[\d+m/, '')

  # Strip the header
  scrubbed_output = scrubbed_output.gsub(/(-{10})[\S\s]*(Terraform.*actions:)/, '')
...
```

## Issue 2
As of Terraform 0.10.4 it seems the 'computed' values are no longer outputting with double quotes. ex:
#### < 0.10.4
```java
+ aws_alb.app
      arn: "<computed>"
```

#### >= 0.10.4
```java
+ aws_alb.app
      arn: <computed>
```

Now im not quite sure how to go about modifying the grammar to accommodate this but a not so clever fix would be in the same function  `TerraformLandscape::Printer.process_string` :
```ruby
def process_string(plan_output)
...
  # Add quotes to '<computed>' values
  unless (match = scrubbed_output.match(/\"<computed>\"/))
    scrubbed_output = scrubbed_output.gsub(/\<computed>/, '"<computed>"')
  end
...
```

**Comment by krobertson** [comment]
Posted a PR which should address both issues.  Thanks for the follow up with some of the specifics you saw... helped a lot with diving in directly.

After merging will ensure a new gem gets pushed.
