### ISSUE TITLE
Error parsing `(new resource required)` in resource header

### ISSUE THREAD

**Issue by NathanTCz** [coinbase/terraform-landscape#35]
In at least Terraform v0.10.5 they have added a new reason to a `resource_header` when a resource is to be re-created `(new resource required)`
```
$ terraform plan

...

-/+ null_resource.foo (tainted) (new resource required)
      id:                    "123456789" => <computed> (forces new resource)
      triggers.%:            "2" => "2"
```

`landscape` throws `error: Expected one of "\n", "\n\n" .... after -/+ null_resource.foo (tainted)`

**Comment by sds** [comment]
Fixed in #36.
