### ISSUE TITLE
Planning to try and get this into core terraform?

### ISSUE THREAD

**Issue by w0rldart** [coinbase/terraform-landscape#48]
Absolutely brilliant extension! Are you planning to try and get it be part of core terraform? Maybe as an argument `--pretty`?

**Comment by BurakDev** [comment]
Nice idea but isn't same way to implement it on original terraform

**Comment by sds** [comment]
Thanks for the kind words, @w0rldart.

We have no plans to implement this in the Terraform project directly, but would love to see that happen!
