### ISSUE TITLE
Error when no resources require any change; Terraform 0.11.2 and Landscape 0.1.17

### ISSUE THREAD

**Issue by jlucktay** [coinbase/terraform-landscape#50]
Hi hi, I found a previous bug #37 that seems to have re-appeared.
When there are no changes from a plan, then Landscape gives an error.

Terraform v0.11.2:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

<super secret client resources redacted>
------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

Landscape v0.1.17:
```
error: Expected [ ] at line 2, column 2 (byte 3) after
-. Use --trace to view backtrace
```

Landscape v0.1.17 with `--trace`:
```
Traceback (most recent call last):
        13: from C:/tools/ruby25/bin/landscape:23:in `<main>'
        12: from C:/tools/ruby25/bin/landscape:23:in `load'
        11: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/bin/landscape:7:in `<top (required)>'
        10: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/lib/terraform_landscape/cli.rb:25:in `run'
         9: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
         8: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
         7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
         6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
         5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
         4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/lib/terraform_landscape/cli.rb:34:in `block (2 levels) in define_commands'
         3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/lib/terraform_landscape/cli.rb:48:in `print'
         2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/lib/terraform_landscape/printer.rb:35:in `process_stream'
         1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/lib/terraform_landscape/printer.rb:69:in `process_string'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/terraform_landscape-0.1.17/lib/terraform_landscape/terraform_plan.rb:36:in `from_output': Expected [ ] at line 2, colum
n 2 (byte 3) after  (TerraformLandscape::TerraformPlan::ParseError)
-
```

More details about this particular environment:
- Windows 7 Enterprise
- PowerShell 4
- Ruby was installed using Chocolatey
- Landscape was installed using Gem

**Comment by sds** [comment]
Hey @jlucktay, I can't reproduce this with Landscape 0.1.17 using Terraform 0.11.2 on Ruby 2.5.0. I'm on macOS and not Windows, but I doubt the OS is the problem here. 

Is there any way you could create a file with redacted/renamed client resources (ideally a minimal example) that reproduces this issue? Remember you can output the plan to a file and then repeatedly cat that file to `landscape` to attempt to reproduce.

```
terraform plan ... > plan.txt
# Modify plan.txt to rename sensitive resources

cat plan | landscape
```

Thanks!

**Comment by jlucktay** [comment]
I'm running this under PowerShell, which I don't think I mentioned initially, and may or may not be relevant.

I'll have a go at generating a text file that causes the error when I'm back on site during the week. Thanks!

**Comment by jlucktay** [comment]
I ran the following commands:
```
terraform plan > plan.txt
cat .\plan.txt | landscape
cat .\plan.txt | landscape --trace
```

[Here is a gist](https://gist.github.com/jlucktay/30abd3b5dd674bf2469dae7a0594dec0) with the outputs from the above commands.

It looks like the colour codes are causing the error! :male_detective:

**Comment by jlucktay** [comment]
I tried `terraform plan -no-color > plan.nocolor.txt` and fed it through Landscape, but it gave the exact same errors, both with just `landscape` as well as `landscape --trace`.

I added `plan.nocolor.txt` to the linked gist as well, for reference.

I guess Landscape doesn't like the array of subnets, in this example?

**Comment by sds** [comment]
Hey @jlucktay, I think information is getting lost somewhere here, possibly when you are copy/pasting into the gist.

When I `wget https://gist.githubusercontent.com/jlucktay/30abd3b5dd674bf2469dae7a0594dec0/raw/df06159f7f9fd087c03b45e605485c4a5e1eb542/plan.nocolor.txt` and then run `cat plan.nocolor.txt | landscape` I don't get any errors. This suggests to me that there are potentially byte sequences being lost somewhere.

Can you run `ruby -e "puts File.read('plan.nocolor.txt').bytes` and post the output to your gist? I'll be able to reconstruct the file appropriate from my side from the raw byte stream. Thanks!

**Comment by jlucktay** [comment]
Hi @sds I added [plan.nocolor.puts.txt](https://gist.githubusercontent.com/jlucktay/30abd3b5dd674bf2469dae7a0594dec0/raw/99a732ef41747e61b15c61377036686310355b16/plan.nocolor.puts.txt) to the gist. Let me know if that helps narrow it down.

**Comment by sds** [comment]
It's odd that your byte stream is interlaced with null bytes (as evidenced by the zeros every other byte).

Can you run `ruby -e "puts File.read('plan.nocolor.txt').encoding"`? I'm not familiar with Ruby on Windows, so there could be some obvious explanation I'm missing here.

**Comment by jlucktay** [comment]
I ran `ruby -e "puts File.read('plan.nocolor.txt').encoding"` and it came back with `CP850`.

Had a quick read of [its Wikipedia page](https://en.wikipedia.org/wiki/Code_page_850) and it seems like this laptop the client has supplied is quite ancient indeed...

**Comment by sds** [comment]
I think the fundamental problem here is that your system is generating files with an encoding that is not compatible with UTF-8. There may be a way around this, but it would require you to investigate on your side.

I don't understand why `terraform` (which is written in Go) would be outputting characters encoded as `CP850`. There must be something else going on with how your system is configured to lead to that.

I'm happy to accept a pull request that fixes this, but won't be investigating further. Thanks!

**Comment by jlucktay** [comment]
Not a problem, and thank you for helping to diagnose!
