### ISSUE TITLE
Support `terraform apply`?

### ISSUE THREAD

**Issue by glenjamin** [coinbase/terraform-landscape#53]
As `terraform apply` now produces a diff and then prompts for a `yes` to apply, it would be neat if landscape could handle this too.

I hope this would mostly be a case of streaming the output through rather than buffering - but it might be more involved.

**Comment by sds** [comment]
Hey @glenjamin, would love to merge a pull request adding support for streaming!

**Comment by glenjamin** [comment]
I had a bit of a look into this. It seems doable but a bit more invasive than i'd initially hoped.

A high level outline of what is required to do this properly:

- [ ] modify grammar to remove `plan` and `resource_list`
- [ ] Flip `Printer.process_stream` and `process_string` around, so print delegates to stream
- [ ] Have stream read in lines at a time and apply the exclusion regexes
- [ ] Feed those lines into the parser one at a time
- [ ] Modify the `TerraformPlan` code to work on chunks - see this [treetop thread](https://groups.google.com/forum/#!searchin/treetop-dev/stream%7Csort:date/treetop-dev/wAEtuGId8MU/4R76PRybRxQJ)
- [ ] Modify the printer to spit out chunk at a time too?

This would be cool as you'd also get incremental feedback - and could even maybe pass-through some of the underlying terraform incremental feedback messages?

While writing this up I realised this is overthinking it somewhat, and there's a cheat's way to do this:

- [ ] Tweak `Printer.process_stream` so that it also treats the `apply` prompt as the end of the input
- [ ] After outputting the formatted plan, output our own prompt

I'm going to have a go at the latter at some point, and I might have a go at the former if i'm feeling adventurous.

**Comment by sds** [comment]
Implemented in #54.

**Comment by glenjamin** [comment]
Do you think it's worth leaving an issue open for full streaming support in case someone else runs into it and wants to give it a go?
