### ISSUE TITLE
latest stable release version? 0.1.17 or 0.1.18?

### ISSUE THREAD

**Issue by ilovezfs** [coinbase/terraform-landscape#55]
https://github.com/coinbase/terraform-landscape/releases/latest shows 0.1.17 but https://github.com/coinbase/terraform-landscape/releases indicates there is a 0.1.18

**Comment by sds** [comment]
Thanks for catching, @ilovezfs. This is now fixed.

**Comment by ilovezfs** [comment]
@sds you're welcome! Voilà: https://github.com/Homebrew/homebrew-core/pull/28920

**Comment by ilovezfs** [comment]
@sds same question regarding 0.2.0
