### ISSUE TITLE
Provide option to fallback on original Terraform output when parser error occurs

### ISSUE THREAD

**Issue by sdduursma** [coinbase/terraform-landscape#58]
Sometimes Terraform Landscape encounters an error while parsing the output from Terraform. It would be useful if Landscape provided an option to fallback on the original Terraform output when this happens.

**Comment by sdduursma** [comment]
I'm preparing a PR to add a `--fallback` flag that, when set, ensures Landscape falls back to the original Terraform output when an error occurs.

**Comment by sds** [comment]
Thanks for the suggestion and pull request, @sdduursma!

Thinking about this, I have a hard time seeing a situation where you don't want this as the default behavior. Can we potentially invert the logic you've implemented to instead have a `--debug` flag that allows you to fall back to displaying the stack trace, but by default will gracefully return the original ouput?

Would love to hear your thoughts.

**Comment by sdduursma** [comment]
Hi @sds, yes I think that makes sense. We can probably find some time to do that in the next couple of weeks.

**Comment by o6uoq** [comment]
+1

**Comment by sdduursma** [comment]
Hey @sds, I've pushed a commit to make the fallback behaviour default. It also allows getting the stack trace by supplying the `--trace` option.

**Comment by sds** [comment]
Implemented in #59. Thanks!
