### ISSUE TITLE
Render base64 as diffable text

### ISSUE THREAD

**Issue by rwolfson** [coinbase/terraform-landscape#72]
It would be nice if base64 were decoded into readable text, and diff'ed. The main use case that comes to mind is Amazon EC2 user data, but there may be other use cases.

**Comment by ryanschneider** [comment]
BTW if this is ever implemented keep in mind that sometimes the base64-encoded value is a gzipped binary stream and not plaintext.

**Comment by sds** [comment]
Tracking in #108.
