### ISSUE TITLE
Publish image on Docker Hub

### ISSUE THREAD

**Issue by MPV** [coinbase/terraform-landscape#79]
Hi, 
Would you be open to publishing a Docker image for Landscape somewhere, like on Docker Hub?

This describes how to create an automated build on Docker Hub from a GitHub repo:
https://docs.docker.com/docker-hub/builds/

**Comment by FernandoMiguel** [comment]
How do you see sending the plan from terraform to landscape, running it from a docker?

**Comment by MPV** [comment]
@FernandoMiguel Like this:
```bash
terraform plan ... | docker run -i --rm landscape
```
-- Source: https://github.com/coinbase/terraform-landscape/blob/master/README.md#docker

I've also confirmed that it works by using this forked image:
https://hub.docker.com/r/wanderadock/terraform-landscape

A drawback with that particular image is that it isn't connected to this repo. Thus it doesn't auto-build new versions of the image when this repo releases new versions (which is nowadays easy to do with the Docker Hub "Automated Builds").

**Comment by sds** [comment]
We will not be maintaining a Docker image under the `coinbase` name in Docker Hub. Closing this out.
