### ISSUE TITLE
Color palette option for red-green color blindness

### ISSUE THREAD

**Issue by bajorgensen** [coinbase/terraform-landscape#84]
This looks really useful, but for 5% of the male population that is red-green color blind I think this might not work very well.
Perhaps it would be useful to offer an option for red-green color blind people?

https://usabilla.com/blog/how-to-design-for-color-blindness/

**Comment by sds** [comment]
Closing this in favor of the more generic request (#94) to support custom output formatters. Would not say no to a pull request adding such support!
