### ISSUE TITLE
Bug: Output formatter rounding down (and up?) numbers in strings

### ISSUE THREAD

**Issue by rafaelmagu** [coinbase/terraform-landscape#92]
It appears floats are being rounded incorrectly.

Original plan shows:

```
~ module.stack.module.eks-cluster.aws_eks_cluster.cluster
     version: "1.11" => "1.10"
```

Landscape output shows:

```
~ module.stack.module.eks-cluster.aws_eks_cluster.cluster
     version: "1.11" => "1.1"
```

As displayed on our Terraform pipeline:
![image](https://user-images.githubusercontent.com/197444/56335289-0a0a4000-61f0-11e9-8ca2-bd6fe19a93a4.png)

**Comment by FernandoMiguel** [comment]
Welcome to yaml
Always quote

**Comment by rafaelmagu** [comment]
It’s not yaml, and the values were quoted.

However I realised I’m using scenery instead of landscape 😂
