### ISSUE TITLE
show just resource names?

### ISSUE THREAD

**Issue by red8888** [coinbase/terraform-landscape#95]
doesnt seem like it takes any args yet so this is probably a feature request

Can it just show me the _names_ of resources that are going to be changed/deleted/added?

**Comment by sds** [comment]
Open to a pull request adding this functionality if it is desired.

**Comment by sds** [comment]
Closing, as this functionality can accomplished with `grep`.

```bash
terraform plan ... | landscape | grep -E '[~+-] [a-zA-Z0-9_-]+'
```

Note: this could be refined further, but the general idea works.
