### ISSUE TITLE
error: undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00000000023de260>

### ISSUE THREAD

**Issue by DimitrisDallas** [coinbase/terraform-landscape#99]
After installing terraform_landscape with `gem install terraform_landscape` successfully, the below error:
`# landscape
Traceback (most recent call last):
        10: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:10:in `<main>'
         9: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
         8: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
         7: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
         6: from /usr/local/rvm/gems/ruby-2.5.1/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
         5: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         3: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         2: from /usr/local/rvm/gems/ruby-2.5.1/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
         1: from /usr/local/rvm/gems/ruby-2.5.1/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/usr/local/rvm/gems/ruby-2.5.1/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00000000023de260> (NoMethodError)`

**Comment by sds** [comment]
I don't see anything in that stack trace that references Terraform Landscape. This seems like an issue with your local Ruby environment or installation.

Terraform Landscape is a vanilla Ruby gem, so we don't do anything to modify your path such that you would expect to see errors such as this.
